#### importing and preprocing

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_excel('bmi.xlsx', sheet_name='Sheet1')
df

Gender  Height  Weight        BMI  Age  Activity_Level Smoker Region
0      Male     174      96  31.708284   56     Very Active    Yes  Urban
1      Male     189      87  24.355421   46     Very Active     No  Rural
2    Female     185     110  32.140248   32     Very Active    Yes  Rural
3    Female     195     104  27.350427   60     Very Active    Yes  Rural
4      Male     149      61  27.476240   25          Active    Yes  Urban
..      ...     ...     ...        ...  ...             ...    ...    ...
495  Female     150     153  68.000000   36  Lightly Active     No  Rural
496  Female     184     121  35.739603   49     Very Active    Yes  Urban
497  Female     141     136  68.407022   18  Lightly Active    Yes  Urban
498    Male     150      95  42.222222   22       Sedentary    Yes  Urban
499    Male     173     131  43.770256   62  Lightly Active     No  Urban

[500 rows x 8 columns]

In [3]:
df.columns


Index(['Gender', 'Height', 'Weight', 'BMI', 'Age', 'Activity_Level', 'Smoker',
       'Region'],
      dtype='object')

In [4]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [5]:
df['Height'].unique()           # heigh is recode in mm

array([174, 189, 185, 195, 149, 147, 154, 169, 159, 192, 155, 191, 153,
       157, 140, 144, 172, 151, 190, 187, 163, 179, 178, 160, 197, 171,
       175, 161, 182, 188, 181, 168, 176, 196, 164, 143, 141, 193, 194,
       180, 165, 166, 186, 198, 145, 183, 177, 170, 142, 199, 150, 146,
       148, 184, 158, 167, 156, 162, 173, 152])

In [6]:
df['Weight'].unique()

array([ 96,  87, 110, 104,  61,  92, 111,  90, 103,  81,  80, 101,  51,
        79, 107, 129, 145, 139, 149,  97,  67,  64,  95,  62, 159, 152,
       121,  52,  65, 131, 153, 132, 114, 120, 108,  56, 118, 126,  76,
       122,  72, 135,  54, 105, 116,  89, 127,  70,  88, 143,  83, 158,
        59,  82, 136, 117,  75, 100, 154, 140, 123,  50, 141, 119, 156,
        69, 155, 160, 106,  66, 157,  60,  57, 138, 115, 151, 150, 147,
       124,  85, 125, 146,  98,  84, 102,  99,  78, 109,  94,  74,  73,
       134, 137, 144,  93,  86, 130,  58, 148,  68,  71,  63,  91, 142,
       133,  77, 128, 112,  55,  53])

In [7]:
df['Age'].unique()

array([56, 46, 32, 60, 25, 38, 36, 40, 28, 41, 53, 57, 20, 39, 19, 61, 47,
       55, 50, 29, 42, 44, 59, 45, 33, 64, 54, 24, 26, 35, 21, 31, 43, 37,
       52, 34, 23, 51, 27, 48, 65, 62, 58, 18, 22, 30, 49, 63])

In [8]:
df['Activity_Level'].unique()

array(['Very Active', 'Active', 'Lightly Active', 'Sedentary'],
      dtype=object)

In [9]:
df['Smoker'].unique()

array(['Yes', 'No'], dtype=object)

In [10]:
df['Region'].unique()

array(['Urban', 'Rural'], dtype=object)

In [11]:
df.isnull().sum()

Gender            0
Height            0
Weight            0
BMI               0
Age               0
Activity_Level    0
Smoker            0
Region            0
dtype: int64

#### Good to go Now...

In [12]:
# Moving Bmi to last
df = df[['Gender', 'Height', 'Weight', 'Age', 'Activity_Level', 'Smoker','Region', 'BMI',]]
df

Gender  Height  Weight  Age  Activity_Level Smoker Region        BMI
0      Male     174      96   56     Very Active    Yes  Urban  31.708284
1      Male     189      87   46     Very Active     No  Rural  24.355421
2    Female     185     110   32     Very Active    Yes  Rural  32.140248
3    Female     195     104   60     Very Active    Yes  Rural  27.350427
4      Male     149      61   25          Active    Yes  Urban  27.476240
..      ...     ...     ...  ...             ...    ...    ...        ...
495  Female     150     153   36  Lightly Active     No  Rural  68.000000
496  Female     184     121   49     Very Active    Yes  Urban  35.739603
497  Female     141     136   18  Lightly Active    Yes  Urban  68.407022
498    Male     150      95   22       Sedentary    Yes  Urban  42.222222
499    Male     173     131   62  Lightly Active     No  Urban  43.770256

[500 rows x 8 columns]

#### Encoding The data

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
x = df[['Gender','Height', 'Weight', 'Age', 'Activity_Level', 'Smoker','Region']]
y = df['BMI']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=False)

In [15]:
x_test


Gender  Height  Weight  Age  Activity_Level Smoker Region
90   Female     178     154   58       Sedentary    Yes  Urban
254    Male     183     147   57       Sedentary    Yes  Rural
283    Male     166     107   41     Very Active    Yes  Urban
445    Male     159     140   40       Sedentary     No  Urban
461    Male     152     132   39  Lightly Active    Yes  Urban
..      ...     ...     ...  ...             ...    ...    ...
372    Male     185      60   64  Lightly Active     No  Urban
56     Male     172      92   52       Sedentary    Yes  Urban
440  Female     172     116   36          Active    Yes  Urban
60   Female     191      54   57       Sedentary    Yes  Rural
208    Male     191      96   19     Very Active     No  Rural

[100 rows x 7 columns]

In [16]:
x_train

Gender  Height  Weight  Age  Activity_Level Smoker Region
107    Male     159     154   52     Very Active    Yes  Urban
336  Female     167     153   50          Active     No  Urban
71     Male     178     117   27     Very Active    Yes  Urban
474  Female     167      79   47  Lightly Active     No  Rural
6      Male     147      92   56       Sedentary     No  Urban
..      ...     ...     ...  ...             ...    ...    ...
323    Male     187     140   47       Sedentary     No  Rural
192    Male     165     105   50          Active     No  Rural
117  Female     146     104   29          Active     No  Rural
47     Male     181     111   43  Lightly Active     No  Urban
172    Male     167     151   61       Sedentary     No  Rural

[400 rows x 7 columns]

In [17]:
y_train

107    60.915312
336    54.860339
71     36.927156
474    28.326580
6      42.574853
         ...    
323    40.035460
192    38.567493
117    48.789642
47     33.881750
172    54.143211
Name: BMI, Length: 400, dtype: float64

In [18]:
y_test

90     48.604974
254    43.895010
283    38.830019
445    55.377556
461    57.132964
         ...    
372    17.531045
56     31.097891
440    39.210384
60     14.802226
208    26.315068
Name: BMI, Length: 100, dtype: float64

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_val = ['Gender', 'Activity_Level', 'Smoker', 'Region']
numeric_val = ['Height', 'Weight', 'Age']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first'), categorical_val),
        ('num', 'passthrough', numeric_val)
    ]
)

x_train_enc = preprocessor.fit_transform(x_train)
x_test_enc = preprocessor.transform(x_test)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train_enc, y_train)

y_pred = model.predict(x_test_enc)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)

print(f"Test MSE: {mse:.2f}")


Test MSE: 5.56
